package com.earnsafe.service;

import com.earnsafe.dto.response.PremiumCalculationResponse;
import com.earnsafe.entity.User;
import com.earnsafe.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;

@Service
@RequiredArgsConstructor
public class PremiumService {

    private final UserRepository userRepository;
    private final RiskService riskService;

    public PremiumCalculationResponse calculate(User user) {
        AiInferenceService.RiskPrediction prediction = riskService.calculateRiskForUser(user);
        BigDecimal basePremium = new BigDecimal("39.00");
        BigDecimal finalPremium = prediction.premium().setScale(2, RoundingMode.HALF_UP);

        return PremiumCalculationResponse.builder()
                .basePremium(basePremium)
                .finalWeeklyPremium(finalPremium)
                .riskScore(prediction.riskLevel())
                .riskScoreNumeric(Math.round((prediction.riskScore() / 100.0) * 100.0) / 100.0)
                .breakdown(List.of(
                        new PremiumCalculationResponse.BreakdownItem("Base weekly premium", basePremium),
                        new PremiumCalculationResponse.BreakdownItem("AI risk adjustment", finalPremium.subtract(basePremium))
                ))
                .explanation("Premium is generated by ML risk scoring using location, weather, claims history, and worker activity.")
                .build();
    }

    public PremiumCalculationResponse calculateForUser(Long userId) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));
        return calculate(user);
    }
}
