package com.earnsafe.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ClaimResponse {
    private Long id;
    private String claimNumber;
    private Long userId;
    private String userFullName;
    private Long policyId;
    private String policyNumber;
    private String triggerType;
    private LocalDate disruptionDate;
    private String city;
    private String zone;
    private BigDecimal estimatedLostHours;
    private BigDecimal estimatedLostIncome;
    private String validationStatus;
    private String claimStatus;
    private Boolean fraudFlag;
    private String fraudReason;
    /** Numeric fraud score in [0.0, 1.0] from FraudService */
    private Double fraudScore;
    /** UUID-based transaction ID generated by PayoutService */
    private String transactionId;
    private BigDecimal payoutAmount;
    private String payoutStatus;
    private Boolean payoutRetryPending;
    private Integer payoutRetryCount;
    private String payoutFailureReason;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
